name: "Deploy VPS"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
        - name: "Baixar código"
          uses: actions/checkout@v4

        - name: "Copiar arquivos VPS"
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.VPS_HOST }}
            username: ${{ secrets.VPS_USERNAME }}
            port: ${{ secrets.VPS_PORT }}
            password: ${{ secrets.VPS_PASSWORD }}
            source: "."
            target: ${{ secrets.VPS_TARGET }}

        - name: "Build deploy"
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.VPS_HOST }}
            username: ${{ secrets.VPS_USERNAME }}
            port: ${{ secrets.VPS_PORT }}
            password: ${{ secrets.VPS_PASSWORD }}
            script: |
              cd ${{ secrets.VPS_TARGET }}
              pm2 restart dice-app || pm2 start start.js --name dice-app