name: "Deploy VPS"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
        - name: "Baixar código"
          uses: actions/checkout@v4

        - name: "Configurar Node.js"
          uses: actions/setup-node@v4
          with:
            node-version: "22.18.0"
            cache: "npm"

        - name: "Instalar dependências"
          run: npm ci

        - name: "Rodar Prisma"
          run: npx prisma generate

        - name: "Build projeto"
          run: npm run build
          env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
            NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}

        - name: "Deploy para VPS"
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.VPS_HOST }}
            username: ${{ secrets.VPS_USERNAME }}
            port: ${{ secrets.VPS_PORT }}
            password: ${{ secrets.VPS_PASSWORD }}
            script: |
              cd ${{ secrets.VPS_TARGET }}
              pm2 stop dice || echo "Aplicação não estava rodando"
              git pull origin main
              npm ci --production
              npx prisma generate
              npx prisma migrate deploy || echo "Migração falhou"
              npm run build
              pm2 start dice || pm2 restart dice