name: "Deploy VPS Hostinger"

on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
        - name: "Checkout código"
          uses: actions/checkout@v4

        - name: "Configurar Node.js"
          uses: actions/setup-node@v4
          with:
            node-version: "22"
            cache: "npm"

        - name: "Deploy para VPS"
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.VPS_HOST }}
            username: ${{ secrets.VPS_USERNAME }}
            port: ${{ secrets.VPS_PORT }}
            password: ${{ secrets.VPS_PASSWORD }}
            script: |
              export PATH="/usr/bin:/usr/local/bin:$PATH"
              source ~/.bashrc || true
              source ~/.profile || true

              if ! command -v node &> /dev/null; then
                  curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
                  sudo apt-get install -y nodejs
              fi

              if ! command -v pm2 &> /dev/null; then
                  npm install -g pm2
              fi
              cd ${{ secrets.VPS_TARGET }}
              pm2 stop dice || echo "Aplicação não estava rodando"
              git pull origin main
              npm ci --production
              npx prisma generate
              npx prisma migrate deploy || echo "Nenhuma migração pendente"
              npm run build
              pm2 start dice || pm2 restart dice
              pm2 status